# Generated by Django 5.2.5 on 2025-09-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
