# Generated by Django 5.2.5 on 2025-09-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
